# -*- coding: utf-8 -*-
from gettext import gettext as _

PYRAMID = [_('sweets'), _('dairy'), _('fruits'), _('meat'), _('grains'),
           _('vegetables')]
# name, calories, food pyramid group, image name
NAME = 0
CALS = 1
GROUP = 2
IMAGE = 3
FOOD_DATA = [
_('aguacate'), 151, 2, 'aguacate.png',
_('apio'), 19, 5, 'apio.png',
# _('apple'), 72, 2, 'apple.png',
_('arroz'), 343, 4, 'arroz.png',
_('avena'), 387, 4, 'avena.png',
_('ayote'), 37, 5, 'ayote.png',
# _('banana'), 105, 2, 'banana.png',
_('banano'), 90, 2, 'banano.png',
# _('beef'), 284, 3, 'beef.png',
_('berenjena'), 26, 5, 'berenjena.png',
_('bread'), 69, 4, 'bread.png',
# _('broccoli'), 55, 5, 'broccoli.png',
_('brócoli'), 14, 5, 'brocoli.png',
_('cacao'), 343, 4, 'cacao-fruto.png',
_('cake'), 387, 0, 'cake.png',
_('cebada'), 350, 4, 'cebada.png',
_('cebolla'), 40, 5, 'cebolla.png',
_('cerdo'), 194, 3, 'cerdo.png',
_('cereza'), 60, 2, 'cereza.png',
_('chayote'), 30, 5, 'chayote.png',
# _('cheese'), 114, 1, 'cheese.png',
# _('chicken'), 262, 3, 'chicken.png',
_('chile'), 23, 5, 'chile.png',
_('chiltoma'), 48, 5, 'chiltoma.png',
_('coco'), 300, 2, 'coco.png',
_('cookie'), 68, 0, 'cookie.png',
# _('corn'), 96, 4, 'corn.png',
_('crema'), 340, 1, 'crema.png',
_('egg'), 77, 3, 'egg.png',
_('elote'), 96, 5, 'elote.png',
# _('fish'), 58, 3, 'fish.png',
_('fresa'), 23, 2, 'fresa.png',
_('guayaba'), 55, 2, 'guayabas.png',
_('leche'), 57, 1, 'leche.png',
_('lechuga'), 19, 5, 'lechuga.png',
_('limón'), 30, 2, 'limon.png',
_('linaza'), 450, 4, 'linaza.png',
_('maíz'), 346, 4, 'maiz.png',
_('mandarina'), 44, 2, 'mandarina.png',
_('mango'), 73, 2, 'mango.png',
_('manzana'), 65, 2, 'manzana.png',
_('melocotón'), 63, 2, 'melocoton.png',
_('melón'), 80, 2, 'melon.png',
_('naranja'), 38, 2, 'naranja.png',
_('níspero'), 50, 2, 'nispero.png',
# _('orange'), 62, 2, 'orange.png',
_('papa'), 90, 5, 'papa.png',
_('papaya'), 25, 2, 'papaya.png',
_('pepino'), 12, 5, 'pepino.png',
_('pera'), 61, 2, 'pera.png',
_('pescado'), 91, 3, 'pez.png',
_('piña'), 55, 2, 'pina.png',
_('pipian'), 16, 5, 'pipian.png',
_('pitahaya'), 36, 2, 'pitaya.png',
_('plátano'), 86, 5, 'platano.png',
_('pollo'), 170, 3, 'pierna-de-pollo.png',
# _('potato'), 159, 5, 'potato.png',
_('queso'), 07, 1, 'queso.png',
_('rábano'), 16, 5, 'rabano.png',
_('remolacha'),	43, 5, 'remolacha.png',
_('repollo'), 40, 5, 'repollo.png',
_('res'), 180, 3, 'res.png',
# _('rice and beans'), 411, 4, 'rice-and-beans.png',
_('sandia'), 47, 2, 'sandia.png',
_('semilla de jícaro'), 30, 4, 'semillas-de-jicaro.png',
# _('sweetpotato'), 169, 5, 'sweetpotato.png',
_('tamale'), 126, 5, 'nacatamal.png',
_('tomate'), 16, 5, 'tomate.png',
# _('tomato'), 150, 5, 'tomato.png',
_('trigo'), 345, 4, 'trigo.png',
_('uva'), 68, 2, 'uvas.png',
# _('water'), 0, 6, 'water.png',
_('yogurt'), 38, 1, 'yogurt.png'
_('yuca'), 120, 5, 'yuca.png',
_('zanahoria'), 37, 5, 'zanahoria.png',
_('zapote'), 52, 2, 'zapote.png',
]
